### ISSUE TITLE
Shape and Sprite design and API improvements

### ISSUE THREAD

**Issue by tmontes** [tmontes/python-aturtle#15]
What things are:
* [x] #16 Images should be named shapes of which there are, at least, two kinds: vector and bitmap.
* Sprites are Images on a Canvas:
  * They support placement and rotation.
  * Will support async-based animation and, who knows, collision detection? :)

Let's improve the consistency across shapes/sprites and vector/bitmap classes:
* [x] Rotation is currently implemented in the sprite for vector based sprites but in the underlying image, for bitmap based sprites. Here's an idea:
  * [x] #18 All images (to be named shapes) will be used via an index, much like the current `Bitmap` image. Such access returns a usable "payload" that Sprites "put" on the canvas.
  * [x] #20 Move rotation code to the vector shapes.
  * [x] #20 Allow "rotated payloads" to be i) pre-computed (as in current `Bitmap`) or ii) computed on demand and cached.
  * [x] #18 Along those lines, let's allow `Bitmap` rotations to also be i) pre-computed or ii) computed on demand and cached.
* [x] #19 Visual information should belong to the shape as identified in #10. Sprites use that for rendering. Refactor vector sprites/images with regards to this.
* [x] #17 Bitmap images should use `anchor` argument instead of `cx`, `cy`.
* [x] #18 The previous points induce the creation of an image (Shape!) base class.

More:
* [x] #21 Review anchor consistency all around. Sometimes (x, y) tuple, others two separate values.
* [x] #32 Review Sprite API:
  * [x] Want to have read or write access to underlying shape? Maybe not for now. Later may be interesting for "character" animations. But later. Deferred to #33.
  * [x] #22 Rename the `sprite` package to `sprites`, for consistency with `shapes`.
  * [x] #24 Improve the sprite creation function in the package. Idea: when given an `str` assume it's an image filename, when given `bytes` assume it's image data, if it's a list assume a list of points, otherwise, assume a vector shape.
* [x] #23 DRY up the names: why have `VectorShape` in a `shape.vector` module? Mutatis mutants for other vector/bitmap and shape/sprite combinations. :-)
* [x] #30 User facing angles should be in degrees (instead of radians) which are more intuitive to most, especially beginners.
* [x] #30 review the shapes API.

**Comment by tmontes** [comment]
Closing:
* APIs are cleaner.
* Tests are in place.
